pingswept/pysolar

pysolar/solar.py
Corrected approximation according to NREL's C code (http://www.nrel.gov/midc/spa/)
Now the function is only applied if the sun is not close to horizon
=> corrected get_refraction_correction

pysolar/time.py
I noticed that when calculating dates after the last leap second in the
table, a user warning is issued. This is good, as I otherwise would not
have known that leap seconds are handled as a constant.
This patch adds the 2015 leap second to the constant list, bringing it
up to date.
=> Add 2015 leap second

pysolar/time.py
Add leap second to 2016 per [IERS Bulletin C](https://hpiers.obspm.fr/iers/bul/bulc/bulletinc.dat), published July 6th 2016.
=> Add leap second for 2016

.travis.yml, README.markdown
Run testcases using [Travis](https://travis-ci.org/). The testcases are automatically executed on pushes + on PRs to ensure the project's testcases pass on Python 3.4 up to 3.7-dev.
* On the main page there is a badge with the current build status ([example](https://github.com/quinox/pysolar/tree/travis-quinox))
* This badge links to the results of Travis ([example](https://travis-ci.org/quinox/pysolar))
One time setup is easy:
* Visit https://travis-ci.org/
* Login through Github OAuth (no account at Travis required)
* Enable testing for *pingswept/pysolar*
* Merge this PR.
=> Add Travis integration

pysolar/util.py
It looks like there is a grave bug with missing degrees to radians conversions in trigonometric function calls in radiation equation. Should be fixed with this patch.
=> Added missing deg/rad conversions in util.extraterrestrial_irrad()

pysolar/solar.py, pysolar/solartime.py, test/testsolar.py
get_azimuth and get_altitude had a lot of common code.
combining them into get_position avoids running the common code twice.
Signed-off-by: Eliot Blennerhassett <eliot@blennerhassett.gen.nz>
=> Refactor get_azimuth, get_altitude. Add get_position

pysolar/solartime.py
> Calendar is a table or register with the days of each month and week in a year.
> Calender is a machine in which cloth or paper is pressed by rollers to glaze or smooth it.
> Calendar and calender are pronounced the same but have different spellings and meanings. “Calender” is rarely used in English writing but it is a frequent misspelling of the much more common word “calendar”.
=> Minor typo fix

pysolar/__init__.py, pysolar/elevation.py, pysolar/numeric.py, pysolar/radiation.py, pysolar/rest.py, pysolar/simulate.py, pysolar/solar.py, pysolar/util.py, test/test_numpy.py
This is a first step towards #72, that I implemented for my needs.
Introduced the module numeric.py to include common functions between math and numpy, and some tools to help in the vectorization.
numpy is only an optional dependency, which allows to pass arrays of latitudes and longitudes to get_elevation and get_azimuth. However, times still can not be passed as arrays because some functions in solartime.py are not very straightforward to vectorize.
This approach could be extended to more functions in pysolar.
Let me know what you think of this approach.
=> Make get_elevation and get_azimuth numpy-aware

pysolar/numeric.py, pysolar/solar.py, pysolar/tzinfo_check.py, test/test_numpy.py
This allows applying `get_altitude_fast` and `get_azimuth_fast` to numpy datetime64 arrays.
=> solar.py: time vectorization of *_fast functions

pysolar/util.py
It seems in some scenarios i observed `KT > 1` and `ZeroDivisionError`. So these changes might help.
=> Changes to Clearness index function which should return  values between 0 and 1

pysolar/numeric.py
ModuleNotFoundError was introduced in Python 3.6 as a more specific
subclass of ImportError. We need to fall back to the more generic
ImportError to ensure Python 3.5 and 3.4 compatibility.
=> Fix #97 -- Raise ImportError

pysolar/util.py
Reverts pingswept/pysolar#104
This broke the build with this error on Python 3.4:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
=> Revert "Changes to Clearness index function which should return  values between 0 and 1"

pysolar/radiation.py, test/test_numpy.py
As another increment toward issue #72, I got `get_radiation_direct` to work with NumPy arrays as inputs.
The existing tests pass on the Python interpreter I was using (3.7.0), and I added a new test to exercise the new functionality.
=> Make get_radiation_direct handle NumPy arrays

pysolar/util.py
Reverts pingswept/pysolar#117
This patch breaks the build for Python 3.7, but only for some silly reason. I'll sort this out eventually. The problem is with the build test, not the patch.
=> Revert "Fix get_sunrise_sunset_transit() function name in example"

.github/workflows/testpackage.yml, pysolar/rest.py, requirements.txt
Hello,
I noticed the issue with the recent pull request to remove pytz failing test. Enabling automated tests with GitHub Actions would flag these issues easily. Here I've just used the standard template recommended by GitHub to test Python packages.
**Note:** the linting found a bunch of issues in the `rest.py` file with undefined variable names which I did not know how to fix, so I commented out the linter from the test definitions. You should look into it before re-enabling linting.
Thanks for your work on Pysolar!
Francois
=> Automated testing with GitHub actions

python3-pysolar.spec
With these changes to the spec file, pysolar builds with python3 on Fedora 32 and CentOS 8 (python2 is deprecated, so I didn't bother with it). Except in these systems, I haven't tried in other systems than CentOS 7 where it doesn't build due to missing libraries. It is a bit unclear to me which runtime dependencies pysolar requires (e.g. numpy?). Maybe at least python3 should be added as a Requires to the spec file. If someone knows, I can add it.
=> Removed python2. Added build deps.

.github/workflows/testpackage.yml, CONTRIBUTORS.markdown, pysolar/solar.py, python3-pysolar.spec, requirements.txt, setup.py
Final changes to completely remove dependency on `pytz`.
Also `nose` is not a dependency of the package as installed as it's exclusively used in `test/test_numpy.py`, so moved its installation to `.github\testpackage.yaml`
=> Final cleanup to remove unneeded dependencies

pysolar/util.py
Hi, I've been using the get_sunrise_sunset_transit function to calculate the sunrise, sunset and transit time in my current location, using my local timezone.
The problem is that this function calculates the sunrise, sunset and transit time of the UTC day in local time, but would be more logic to calculate the sunrise, sunset and transit time of the current local day in local time.
For example:
I'm in Madrid timezone (+1), and when I calculate the sunrise time at local time 29/11/2020_00:30:00 (UTC 28/11/2020_23:30:00) it correctly gives me back the sunrise time in local time, but from the day 28 not from the 29.
I've removed 'utc' from 'utctimetuple()' which gets rid of that behavior. 
I don't really know if this behavior has been implemented on purpose but for the current program I'm …
=> get_sunrise_sunset_transit referred to UTC not to local time

pysolar/solartime.py
I've added leap second information for 2022 as per the [NIST page](https://www.nist.gov/pml/time-and-frequency-division/atomic-standards/leap-second-and-ut1-utc-information) you referenced.
=> Add leap second information for 2022

setup.py
`requires` is superseded by `install_requires` and should not be used anymore. 
Reference: https://setuptools.pypa.io/en/latest/references/keywords.html
=> Use install_requires keyword in setup.py

pysolar/solartime.py
The current message caused some confusion for me. I updated it to something that is hopefully more clear
=> Change warning message for leap seconds

pysolar/solartime.py
No leap second introduced. Next likely update : December 31, 2024.
=> Leap Second for 2024

pysolar/util.py
The previous implementation of the function get_sunrise_sunset_transit worked perfectly previous to bf02e56d7412ce9910ba084ef538f8276acc36dc.
I've restored the previous code, which gives identical results as the original C code (with respect to which day to use).
I'll give a detailed explanation and tests in #144 discussion.
=> Solves #144 by going back to previous implementation of get_sunrise_sunset_transit function.

doc/index.rst
Changes `http://www.clearskyinstitute.com/xephem` to `https://xephem.github.io/XEphem/Site/xephem`.
Cheers, Tom
=> Fixes link to XEphem
